# Clustering Crypto

In [88]:
# Initial imports
import pandas as pd
import hvplot.pandas
from path import Path
import plotly.express as px
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans


### Deliverable 1: Preprocessing the Data for PCA

In [89]:
# Load the crypto_data.csv dataset.
file_path = "crypto_data.csv"
df_crypto = pd.read_csv(file_path, index_col=0)
df_crypto.head()

CoinName Algorithm  IsTrading ProofType  TotalCoinsMined TotalCoinSupply
42     42 Coin    Scrypt       True   PoW/PoS     4.199995e+01              42
365    365Coin       X11       True   PoW/PoS              NaN      2300000000
404    404Coin    Scrypt       True   PoW/PoS     1.055185e+09       532000000
611  SixEleven   SHA-256       True       PoW              NaN          611000
808        808   SHA-256       True   PoW/PoS     0.000000e+00               0

In [90]:
# Keep all the cryptocurrencies that are being traded.
df_crypto_trading = df_crypto[df_crypto.IsTrading == True]
df_crypto_trading.head()

CoinName Algorithm  IsTrading ProofType  TotalCoinsMined TotalCoinSupply
42     42 Coin    Scrypt       True   PoW/PoS     4.199995e+01              42
365    365Coin       X11       True   PoW/PoS              NaN      2300000000
404    404Coin    Scrypt       True   PoW/PoS     1.055185e+09       532000000
611  SixEleven   SHA-256       True       PoW              NaN          611000
808        808   SHA-256       True   PoW/PoS     0.000000e+00               0

In [91]:
# Remove the "IsTrading" column. 
df_crypto_dropTrading = df_crypto_trading.drop('IsTrading', axis='columns')
df_crypto_dropTrading.head()

CoinName Algorithm ProofType  TotalCoinsMined TotalCoinSupply
42     42 Coin    Scrypt   PoW/PoS     4.199995e+01              42
365    365Coin       X11   PoW/PoS              NaN      2300000000
404    404Coin    Scrypt   PoW/PoS     1.055185e+09       532000000
611  SixEleven   SHA-256       PoW              NaN          611000
808        808   SHA-256   PoW/PoS     0.000000e+00               0

In [92]:
# Remove rows that have at least 1 null value.
df_crypto_dropTrading.dropna(inplace=True)
df_crypto_dropTrading.count()

CoinName           685
Algorithm          685
ProofType          685
TotalCoinsMined    685
TotalCoinSupply    685
dtype: int64

In [93]:
# Keep the rows where coins are mined.
df_crypto_coins = df_crypto_dropTrading[df_crypto_dropTrading.TotalCoinsMined > 0]
df_crypto_coins.count()

CoinName           532
Algorithm          532
ProofType          532
TotalCoinsMined    532
TotalCoinSupply    532
dtype: int64

In [94]:
# Create a new DataFrame that holds only the cryptocurrencies names.
df_crypto_names = df_crypto_coins.filter(items=['CoinName'])
df_crypto_names.head()

CoinName
42      42 Coin
404     404Coin
1337  EliteCoin
BTC     Bitcoin
ETH    Ethereum

In [95]:
# Drop the 'CoinName' column since it's not going to be used on the clustering algorithm.
df_crypto_dropCoinName = df_crypto_coins.drop('CoinName', axis='columns')
df_crypto_dropCoinName.head(10)

Algorithm ProofType  TotalCoinsMined TotalCoinSupply
42            Scrypt   PoW/PoS     4.199995e+01              42
404           Scrypt   PoW/PoS     1.055185e+09       532000000
1337             X13   PoW/PoS     2.927942e+10    314159265359
BTC          SHA-256       PoW     1.792718e+07        21000000
ETH           Ethash       PoW     1.076842e+08               0
LTC           Scrypt       PoW     6.303924e+07        84000000
DASH             X11   PoW/PoS     9.031294e+06        22000000
XMR   CryptoNight-V7       PoW     1.720114e+07               0
ETC           Ethash       PoW     1.133597e+08       210000000
ZEC         Equihash       PoW     7.383056e+06        21000000

In [96]:
# Use get_dummies() to create variables for text features.
X = pd.get_dummies(df_crypto_dropCoinName, columns=['Algorithm', 'ProofType'])
X.head(10)

TotalCoinsMined TotalCoinSupply  Algorithm_1GB AES Pattern Search  \
42       4.199995e+01              42                                 0   
404      1.055185e+09       532000000                                 0   
1337     2.927942e+10    314159265359                                 0   
BTC      1.792718e+07        21000000                                 0   
ETH      1.076842e+08               0                                 0   
LTC      6.303924e+07        84000000                                 0   
DASH     9.031294e+06        22000000                                 0   
XMR      1.720114e+07               0                                 0   
ETC      1.133597e+08       210000000                                 0   
ZEC      7.383056e+06        21000000                                 0   

      Algorithm_536  Algorithm_Argon2d  Algorithm_BLAKE256  Algorithm_Blake  \
42                0                  0                   0                0   
404               0                  0                   0                0   
1337              0                  0                   0                0   
BTC               0                  0                   0                0   
ETH               0                  0                   0                0   
LTC               0                  0                   0                0   
DASH              0                  0                   0                0   
XMR               0                  0                   0                0   
ETC               0                  0                   0                0   
ZEC               0                  0                   0                0   

      Algorithm_Blake2S  Algorithm_Blake2b  Algorithm_C11  ...  \
42                    0                  0              0  ...   
404                   0                  0              0  ...   
1337                  0                  0              0  ...   
BTC                   0                  0              0  ...   
ETH                   0                  0              0  ...   
LTC                   0                  0              0  ...   
DASH                  0                  0              0  ...   
XMR                   0                  0              0  ...   
ETC                   0                  0              0  ...   
ZEC                   0                  0              0  ...   

      ProofType_PoW/PoS  ProofType_PoW/PoS   ProofType_PoW/PoW  \
42                    1                   0                  0   
404                   1                   0                  0   
1337                  1                   0                  0   
BTC                   0                   0                  0   
ETH                   0                   0                  0   
LTC                   0                   0                  0   
DASH                  1                   0                  0   
XMR                   0                   0                  0   
ETC                   0                   0                  0   
ZEC                   0                   0                  0   

      ProofType_PoW/nPoS  ProofType_Pos  ProofType_Proof of Authority  \
42                     0              0                             0   
404                    0              0                             0   
1337                   0              0                             0   
BTC                    0              0                             0   
ETH                    0              0                             0   
LTC                    0              0                             0   
DASH                   0              0                             0   
XMR                    0              0                             0   
ETC                    0              0                             0   
ZEC                    0              0                             0   

      ProofType_Proof of Trust  ProofType_TPoS  \
42

In [97]:
# Standardize the data with StandardScaler().
df_crypto_scaled = StandardScaler().fit_transform(X)
print(df_crypto_scaled)

[[-0.11710817 -0.1528703  -0.0433963  ... -0.0433963  -0.0433963
  -0.0433963 ]
 [-0.09396955 -0.145009   -0.0433963  ... -0.0433963  -0.0433963
  -0.0433963 ]
 [ 0.52494561  4.48942416 -0.0433963  ... -0.0433963  -0.0433963
  -0.0433963 ]
 ...
 [-0.09561336 -0.13217937 -0.0433963  ... -0.0433963  -0.0433963
  -0.0433963 ]
 [-0.11694817 -0.15255998 -0.0433963  ... -0.0433963  -0.0433963
  -0.0433963 ]
 [-0.11710536 -0.15285552 -0.0433963  ... -0.0433963  -0.0433963
  -0.0433963 ]]


### Deliverable 2: Reducing Data Dimensions Using PCA

In [98]:
# Using PCA to reduce dimension to three principal components.
pca = PCA(n_components=3)
crypto_pca = pca.fit_transform(df_crypto_scaled)
print(crypto_pca)

[[-0.32245999  1.03533568 -0.54498886]
 [-0.30581992  1.03549691 -0.54545944]
 [ 2.28394367  1.70568326 -0.58191844]
 ...
 [ 0.31291971 -2.28864811  0.33504375]
 [-0.12091655 -2.09598546  0.50239842]
 [-0.28538709  0.79923893 -0.22504334]]


In [99]:
# Create a DataFrame with the three principal components.
pcs_df = pd.DataFrame(data=crypto_pca, columns=["PC1", "PC2", "PC3"], index=df_crypto_dropCoinName.index)
pcs_df.head(10)

PC1       PC2       PC3
42   -0.322460  1.035336 -0.544989
404  -0.305820  1.035497 -0.545459
1337  2.283944  1.705683 -0.581918
BTC  -0.145150 -1.328031  0.155513
ETH  -0.174504 -1.967792  0.347522
LTC  -0.155235 -1.126969 -0.051610
DASH -0.405688  1.220809 -0.386894
XMR  -0.155541 -2.200676  0.323574
ETC  -0.172949 -1.967887  0.347495
ZEC  -0.120915 -2.095985  0.502398

### Deliverable 3: Clustering Crytocurrencies Using K-Means

#### Finding the Best Value for `k` Using the Elbow Curve

In [100]:
# Create an elbow curve to find the best value for K.
inertia = []
k = list(range(1, 11))

for i in k:
   km = KMeans(n_clusters=i, random_state=0)
   km.fit(pcs_df)
   inertia.append(km.inertia_)

elbow_data = {"k":k, "inertia": inertia}
df_elbow = pd.DataFrame(elbow_data)
df_elbow.hvplot.line(x="k", y="inertia", xticks=k, title="Elbow Curve")


:Curve   [k]   (inertia)

Running K-Means with `k=4`

In [101]:
# Initialize the K-Means model.
model = KMeans(n_clusters=3, random_state=5)

# Fit the model
model.fit(pcs_df)

# Predict clusters
predictions = model.predict(pcs_df)

In [102]:
# Create a new DataFrame including predicted clusters and cryptocurrencies features.
# Concatentate the crypto_df and pcs_df DataFrames on the same columns.
clustered_df = df_crypto_dropCoinName.join(pcs_df, how='inner')

#  Add a new column, "CoinName" to the clustered_df DataFrame that holds the names of the cryptocurrencies. 
clustered_df = clustered_df.join(df_crypto_names, how='inner')

#  Add a new column, "Class" to the clustered_df DataFrame that holds the predictions.
clustered_df["Class"] = model.labels_

# Print the shape of the clustered_df
print(clustered_df.shape)
clustered_df.head(10)

(532, 9)


Algorithm ProofType  TotalCoinsMined TotalCoinSupply       PC1  \
42            Scrypt   PoW/PoS     4.199995e+01              42 -0.322460   
404           Scrypt   PoW/PoS     1.055185e+09       532000000 -0.305820   
1337             X13   PoW/PoS     2.927942e+10    314159265359  2.283944   
BTC          SHA-256       PoW     1.792718e+07        21000000 -0.145150   
ETH           Ethash       PoW     1.076842e+08               0 -0.174504   
LTC           Scrypt       PoW     6.303924e+07        84000000 -0.155235   
DASH             X11   PoW/PoS     9.031294e+06        22000000 -0.405688   
XMR   CryptoNight-V7       PoW     1.720114e+07               0 -0.155541   
ETC           Ethash       PoW     1.133597e+08       210000000 -0.172949   
ZEC         Equihash       PoW     7.383056e+06        21000000 -0.120915   

           PC2       PC3          CoinName  Class  
42    1.035336 -0.544989           42 Coin      0  
404   1.035497 -0.545459           404Coin      0  
1337  1.705683 -0.581918         EliteCoin      0  
BTC  -1.328031  0.155513           Bitcoin      1  
ETH  -1.967792  0.347522          Ethereum      1  
LTC  -1.126969 -0.051610          Litecoin      1  
DASH  1.220809 -0.386894              Dash      0  
XMR  -2.200676  0.323574            Monero      1  
ETC  -1.967887  0.347495  Ethereum Classic      1  
ZEC  -2.095985  0.502398             ZCash      1

### Deliverable 4: Visualizing Cryptocurrencies Results

#### 3D-Scatter with Clusters

In [103]:
# Creating a 3D-Scatter with the PCA data and the clusters
fig = px.scatter_3d(clustered_df, x="PC1", y="PC2", z="PC3", color="Class", symbol="Class", width=800, hover_name="CoinName", hover_data=["Algorithm"])
fig.update_layout(legend=dict(x=0,y=1))
fig.show()

In [104]:
# Create a table with tradable cryptocurrencies.
clustered_df.hvplot.table(columns=['CoinName', 'Algorithm', 'ProofType', 'TotalCoinSupply', 'TotalCoinsMined', 'Class'], sortable=True, selectable=True)

:Table   [CoinName,Algorithm,ProofType,TotalCoinSupply,TotalCoinsMined,Class]

In [105]:
# Print the total number of tradable cryptocurrencies.
print(f"There are {clustered_df.CoinName.count()} tradable cryptocurrencies.")

There are 532 tradable cryptocurrencies.


In [106]:
# Scaling data to create the scatter plot with tradable cryptocurrencies.
data = clustered_df[['TotalCoinSupply', 'TotalCoinsMined']]
scaler = MinMaxScaler()
clustered_df = scaler.fit_transform(data)
print(clustered_df)

[[4.20000000e-11 0.00000000e+00]
 [5.32000000e-04 1.06585544e-03]
 [3.14159265e-01 2.95755135e-02]
 ...
 [1.40022261e-03 9.90135079e-04]
 [2.10000000e-05 7.37028150e-06]
 [1.00000000e-06 1.29582282e-07]]


In [107]:
# Create a new DataFrame that has the scaled data with the clustered_df DataFrame index.
plot_df = pd.DataFrame(data=df_crypto_scaled, columns=['TotalCoinsMined', 'TotalCoinSupply'], index=clustered_df.index)

# Add the "CoinName" column from the clustered_df DataFrame to the new DataFrame.
plot_df['CoinName'] = clustered_df['CoinName']

# Add the "Class" column from the clustered_df DataFrame to the new DataFrame. 
plot_df['Class'] = clustered_df['Class']

plot_df.head(10)

AttributeError: 'numpy.ndarray' object has no attribute 'index'

In [ ]:
# Create a hvplot.scatter plot using x="TotalCoinsMined" and y="TotalCoinSupply".
clustered_df.hvplot.scatter(x="TotalCoinsMined", y="TotalCoinSupply", by="Class", hover_cols="CoinName")